package com.lackofsky.cloud_s.service.model

enum class MessageType {
    MESSAGE,USER_CONNECT, USER_UPDATE, USER_INFO_UPDATE, USER_FRIEND_DELETE, STATUS, HANDSHAKE,
    REQUEST
    //FRIEND_REQUEST_TYPE,
//RESPONSE,  //USER, USER_INFO, - нужно ли
//    REQUEST_ADD,REQUEST_CANCEL,REQUEST_DELETE,REQUEST_REJECT,
//    RESPONSE_APPROVED,RESPONSE_CANCELED,RESPONSE_DELETED,RESPONSE_REJECTED
}