package com.lackofsky.cloud_s.service.model

enum class MessageType {
    MESSAGE, USER, USER_INFO, STATUS, HANDSHAKE,
    REQUEST,
    FRIEND_REQUEST_TYPE,
//RESPONSE,  //USER, USER_INFO, - нужно ли
//    REQUEST_ADD,REQUEST_CANCEL,REQUEST_DELETE,REQUEST_REJECT,
//    RESPONSE_APPROVED,RESPONSE_CANCELED,RESPONSE_DELETED,RESPONSE_REJECTED
}